name: .NET Core

on: 
  push:
    branches: 
      - master
      - release/*  

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build with dotnet
      run: |
        dotnet test ./LandLord.Core.Test/Landlord.Core.Test.fsproj
        dotnet test ./LandLord.Shared.Test/LandLord.Shared.Test.csproj
        dotnet build ./LandLord.Shared/LandLord.Shared.csproj
        dotnet build ./LandLord.Core/LandLord.Core.csproj
        dotnet build ./LandLord.Hub/LandLord.Hub.csproj
        dotnet build ./LandLord.BlazorApp/LandLord.BlazorApp.csproj
        dotnet build ./Itminus.LandLord.BlazorExtensions.SignalR.Patch/Itminus.LandLord.BlazorExtensions.SignalR.Patch.csproj
        dotnet build ./LandLord.BlazorApp/LandLord.BlazorApp.csproj
        dotnet build ./LandLord.Web/LandLord.Web.csproj
        
        
