name: LandLord.NET

on: 
  push:
    branches: 
      - master
      - release/*  
  pull_request:
    branches:
    - master

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
        dotnet: [3.0.100]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{matrix.dotnet}}
    - name: Test 
      run: 
        dotnet test ./LandLord.Shared.Test/LandLord.Shared.Test.csproj
        dotnet test ./LandLord.Core.Test/Landlord.Core.Test.fsproj
        dotnet test ./LandLord.Core.Repository.Test/LandLord.Core.Repository.Test.csproj
    - name: Build with dotnet
      run: |
        dotnet build ./LandLord.Shared/LandLord.Shared.csproj
        dotnet build ./LandLord.Core/LandLord.Core.csproj
        dotnet build ./LandLord.Hub/LandLord.Hub.csproj
        dotnet build ./LandLord.BlazorApp/LandLord.BlazorApp.csproj
        dotnet build ./Itminus.LandLord.BlazorExtensions.SignalR.Patch/Itminus.LandLord.BlazorExtensions.SignalR.Patch.csproj
        dotnet build ./LandLord.BlazorApp/LandLord.BlazorApp.csproj
        dotnet build ./LandLord.Web/LandLord.Web.csproj
        
        
